### PR TITLE
Stop logstash-web and prevent it from starting on boot

### LINKED ISSUE #646: logstash: remove logstash-web from deployment
Remove logstash-web from the deployment in order to resolve https://github.com/rcbops/ansible-lxc-rpc/issues/530 and if it's in place then shut it down and prevent it from starting at boot.

### PR DESCRIPTION
**Pull request by odyssey4me**
Resolves https://github.com/rcbops/ansible-lxc-rpc/issues/646 and https://github.com/rcbops/ansible-lxc-rpc/issues/530

### CODE REVIEW

**Comment by stevelle** [comment]
:+1:

**Comment by odyssey4me** [comment]
test this please

**Comment by sigmavirus24** [comment]
:+1:

**Comment by sigmavirus24** [comment]
This seems related to #530 as well

**Comment by cloudnull** [comment]
:+1: LGTM!

**Pull request merged**
