### PR TITLE
Improve container network descriptions

### PR DESCRIPTION
**Pull request by ionosphere80**
I improved the container network descriptions in the
rpc_user_config files.

Fixes rcbops/privatecloud-docs#736

### CODE REVIEW

**Comment by ionosphere80** [comment]
Jenkins: please test this

**Comment by sigmavirus24** [comment]
Jenkins: test this please

**Comment by cloudnull** [comment]
This only effects example file comments and the changes only make understanding the stack better, merging.

**Comment by klevenstein** [comment]
Agree with @ionosphere80 that this should be backported to Icehouse. @cloudnull, thoughts?

**Comment by cloudnull** [comment]
@klevenstein your wish is my command . Backported https://github.com/rcbops/ansible-lxc-rpc/pull/635

**Comment by klevenstein** [comment]
Magical. Thank you!

**Pull request merged**
