### PR TITLE
Changes frozen repo to point to mirror.rackspace.com

### LINKED ISSUE #527: Point frozen repos to Rackspace mirrors
We need to move the frozen repos to point to mirror.rackspace.com/rackspaceprivatecloud instead of rpc-slushee.rackspace.com.

### PR DESCRIPTION
**Pull request by d34dh0r53**
The rpc-slushee.rackspace.com has numerous issues, so
we have created mirror.rackspace.com/rackspaceprivatecloud
to address those issues.  All instances of rpc-slushee
have been replaced.

Fixes #527

### CODE REVIEW

**Comment by stevelle** [comment]
Ansible 1.6.10 is now on the mirror.
LGTM.

**Comment by stevelle** [comment]
Jenkins: test this please

**Comment by stevelle** [comment]
Jenkins: test this please

**Comment by stevelle** [comment]
Jenkins: test this please

**Comment by stevelle** [comment]
Jenkins: test this please

**Comment by sigmavirus24** [comment]
I'm going to be that jerk and ask if there's anyway to not have to change this in so many places if/when we need to update it again. Either way :+1:

**Pull request merged**
