### PR TITLE
Use root pass for galera init script

### PR DESCRIPTION
**Pull request by hughsaunders**
The galera init script uses the debian-sys-maint account to shutdown
mysql. However this password cannot be preseeded, and is randomly
generated on install. Also it is set in the database so must be updated
when replication has been achieved.

This patch implements an alternative: Use the mysql root password for
init script operations (shutdown). This password is preseedable and will
work at any state of replication.

This is no less secure than previous state as we already write root galera
credentials to /root/.my.cnf (0600) and /etc/mysql/debian.cnf is also 0600.

Related: #411

### CODE REVIEW

**Comment by hughsaunders** [comment]
Currently testing, please wait.

**Comment by hughsaunders** [comment]
Tests succeeded, ready for review http://jenkins.propter.net/job/dev-sat6-gate/182/console

**Comment by claco** [comment]
:+1:

**Comment by cloudnull** [comment]
:+1:  - this looks good to me and is a very sensible change. Should this be backported into 9.0.x?

**Comment by mattt416** [comment]
:+1:

**Pull request merged**
