### PR TITLE
heat configuration fixes

### PR DESCRIPTION
**Pull request by miguelgrinberg**
work in progress -- currently testing

### CODE REVIEW

**Comment by cloudnull** [comment]
Looks awesome. Please squash the commits and we'll merge it on through.

**Comment by miguelgrinberg** [comment]
Not ready yet. I'm still getting 401s when I use a SoftwareDeployment resource. Hopefully tomorrow, I'll let you know when it's ready to merge.

**Comment by mattt416** [comment]
Looks good so far @miguelgrinberg.

**Comment by claco** [comment]
Ok, pulling the we need to get better at this card. The rework the commit title/desc into something proper. http://www.slideshare.net/TarinGamberini/commit-messages-goodpractices

**Pull request merged**
