### PR TITLE
swap nova default / fallback repos

### PR DESCRIPTION
**Pull request by jacobwagner**
swapped default and fallback repos for nova, QE was seeing multiple long timeouts when cloning from git.openstack.org

### CODE REVIEW

**Comment by jacobwagner** [comment]
I would recommend this change for 9.0.0 if possible, I have tested it and it makes cloning nova faster with less potential to fail

**Comment by byronmccollum** [comment]
Was seeing the same this afternoon.

**Comment by d34dh0r53** [comment]
The fallback repo should be changed to https://git.openstack.org/cgit/openstack/nova/ as @Apsu pointed out in Issue #188

**Comment by andymcc** [comment]
I'd quite like it if this was uniform - so if all the services had the same cgit/openstack/<service> as their default repo. (or whatever works out as best, but they should all be setup the same)

**Comment by cloudnull** [comment]
Sadly it seems that we can not clone from [ https://git.openstack.org/cgit/openstack/nova ] while the code is browsable it can not be cloned into. in order to clone a repo from git.openstack.org you have to use [ https://git.openstack.org/openstack/nova ].

**Pull request closed without merging**
