### PR TITLE
updated all the things for managed backup

### PR DESCRIPTION
**Pull request by cloudnull**
This commit adds the rpc_support playbook to the default installation which was mandated by the manage backup team.

### CODE REVIEW

**Comment by andymcc** [comment]
@cloudnull this works - LGTM, is this to ensure we backup the other nodes critical items, as long as they dump whatever needs to be backed up into the /var/backup directory? 

I'd like to understand the aim here before merging.

**Comment by cloudnull** [comment]
The is creating the framework for the managed backup team to be able to do whatever it is they need to do. At present, the managed backup team is looking to get everything in the [ /etc/rpc_deploy,  /openstack/backup, /opt/ ]. The /openstack/backup directory is a bind mount on the host which and points to /var/backup in all containers .

**Comment by andymcc** [comment]
@cloudnull got that part, but what is going to go in /var/backup on the individual containers? and how is it getting there?

**Comment by cloudnull** [comment]
This commit was rebased.

**Comment by cloudnull** [comment]
@andymcc the only thing going into /var/backup from within the container is the "holland_backups" which are run as a cron job and done via xtradb dumps per the requirements of our managed backup team. No other containers are doing any type of automated backup at this time. However the changes allows any container to take advantage of the backup directory in the future.

**Pull request merged**
