### PR TITLE
Make cloudserver-aio.sh pull stable/icehouse in the stable/icehouse version

### PR DESCRIPTION
**Pull request by nrb**
This is a fix for #493.

### CODE REVIEW

**Comment by hughsaunders** [comment]
Jenkins: test this please

**Comment by hughsaunders** [comment]
Jenkins: test this please

**Comment by nrb** [comment]
Given that this installs an interfaces file that is solely meant to work in an AIO, I'm not sure if this will ever pass for the Jenkins build labs. As I understand, these jobs are spun up on a hardware clusters, right @hughsaunders?

**Comment by hughsaunders** [comment]
@nrb jenkins should not fail on a change to code that it is not executing. I was retrying all the PRs to see if a particular failure (pip not available) would recur.

**Comment by stevelle** [comment]
:+1:

**Comment by cloudnull** [comment]
:+1:  LGTM.

**Pull request merged**
