### PR TITLE
BACKPORT - proposed/juno - adjust default cpu and ram allocation ratios

### PR DESCRIPTION
**Pull request by cloudnull**
As per support discussion, modify:

nova_cpu_allocation_ratio = 2.0
nova_ram_allocation_ratio = 1.0

Resolves issue: https://github.com/rcbops/ansible-lxc-rpc/pull/579
Cherry Pick from e16c0939ad0f1d6f9da3275f1c8ad5d5db211ab6

### CODE REVIEW

**Comment by cloudnull** [comment]
related issue https://github.com/rcbops/ansible-lxc-rpc/issues/470

**Comment by sigmavirus24** [comment]
Jenkins: test this please

**Comment by sigmavirus24** [comment]
This looks fine to me. I'm curious if we can get the 20+ errors to disappear given we now install lxml. That aside, the 1 tempest failure didn't seem remotely related to this so, :+1:

**Comment by nrb** [comment]
Jenkins: test this please

**Comment by dolph** [comment]
Moved to https://review.openstack.org/139249

**Pull request closed without merging**
