### PR TITLE
Backport to proposed/juno - Change value of SECRET_KEY

### PR DESCRIPTION
**Pull request by sigmavirus24**
Currently SECRET_KEY points to
{ install_lib_dir }}/openstack_dashboard/local/.secret_key_store
however this directory is not writable by www-data:www-data and
attempting to load horizon results in a LockFailed exception being
raised.  Rather than making
{ install_lib_dir }}/openstack_dashboard/local/ writable by
www-data:www-data, we create /var/lib/horizon and point SECRET_KEY to
/var/lib/horizon/.secret_key_stone.

(cherry picked from commit 75b4bbf4fc0be60f22972422f2234836618a12cb)

Conflicts:
    rpc_deployment/inventory/group_vars/horizon.yml

Related-bug: #362

### CODE REVIEW

**Comment by hughsaunders** [comment]
Jenkins: test this please

**Comment by hughsaunders** [comment]
Jenkins: test this please

**Comment by hughsaunders** [comment]
Jenkins: test this please

**Comment by mattt416** [comment]
LGTM

**Pull request merged**
