### PR TITLE
Additional change required for Cinder AZ options

### PR DESCRIPTION
**Pull request by cloudnull**
This commit adds a check to the dynamic inventory script when parsing extra values.
Presently the sciprt expects a dict, however if the user passes a key with a string value 
the inventory parser breaks. This PR simply adds a check to the scrip to ensure that this
does not happen.

Related Issue: https://github.com/rcbops/ansible-lxc-rpc/issues/458

### CODE REVIEW

**Comment by claco** [comment]
@cloudnull backport candidate I assume?

**Comment by ionosphere80** [comment]
I think this explains the problem I found trying to generate inventory on 10.0.0rc3. I could work around the issue by removing the cinder availability zone variables.

**Comment by hughsaunders** [comment]
Jenkins: test this please

**Comment by hughsaunders** [comment]
Jenkins: test this please

**Pull request merged**
