### PR TITLE
Sequential IP addressing dynamic inventory

### PR DESCRIPTION
**Pull request by cloudnull**
This PR changes the way IP addresses are assigned to containers and provider networks.  Support has mentioned that it would be easier for them to have the IP addresses sequentially assigned instead of randomly assigned. This change removes the IP randomization and adds the `container_address` field to the inventory-manage script.

### CODE REVIEW

**Comment by andymcc** [comment]
@cloudnull - this looks like it does work - although it's assigning IPs for the container_address in the mgmt_cidr to the physical hosts (which I don't believe it did before - because these are already set it doesn't really make sense that it does this, you will be wasting x IPs, one for each physical host).

That said, I'm not sure I understand the motivation, what is the major gain from having sequential IPs? You will still need to confirm each container IP since, depending on the size of the environment, the same IPs won't always be for the same containers (and in fact it would be dangerous to assume they are - and potentially just logging into an IP thinking it is container of type x, when it is really a container of type y could cause problems).

I'd like to see a bit more justification in terms of benefits before this gets merged - since we can't guarantee a specific IP ordering for specific containers (solutions can grow and the number of containers of type x could change), having sequential IPs is really no more certain than having dynamic IPs.

**Comment by andymcc** [comment]
This does fail because of the container_addresses assigned to the physical hosts

**Comment by cloudnull** [comment]
This was an oversight on my part. I've gone ahead and updated the PR. Good catch, and thank you.

**Comment by mancdaz** [comment]
closing as deemed unnecessary

**Pull request closed without merging**
