### PR TITLE
This commit allows for more galera/mysql tuning

### LINKED ISSUE #410: Galera Limits not set
Galera container running still with os file limit of 1k although 65K was configured in mariadb, that need to be fixed by using limits.conf. I saw in 9.0.1 this limit was set to 16K, I personally would set it to 128K so the system has more file handles available than actually mariadb allows

### PR DESCRIPTION
**Pull request by cloudnull**
The change allows the user to change the "mysql_max_connections" as variable
If unset, the default will be (100 \* ansible_processor_vcpus). This is based
on the facts gathered by ansible. All galera nodes will be used in computing
the value of the max_connections and the lowest denominator will be used.

This change also modifies the count of wsrep sync thread based on the
the number of CPU cores available on a given host as defined by ansible
facts. This function can also be overridden using the "galera_wsrep_slave_threads"
variable.

Resolves https://github.com/rcbops/ansible-lxc-rpc/issues/410
Related Issue: https://github.com/rcbops/ansible-lxc-rpc/issues/429

### CODE REVIEW

**Comment by claco** [comment]
:+1:

**Comment by Bumblebee-Man** [comment]
Request for back port to 9.0.1. We have a customer who is running into a max connections issue.

**Comment by stevelle** [comment]
also LGTM

**Comment by claco** [comment]
Merging this to master and backporting to stable/icehouse. Has been tested in the wild to fix a current issue.

**Pull request merged**
